# Copyright (c) 2015-2016, NVIDIA CORPORATION. All rights reserved.

CUDA_VERSIONS := 8.0 \
                 7.5 \
                 7.0

CUDNN_VERSIONS := 8.0-cudnn5 \
                  7.5-cudnn5 \
                  7.5-cudnn4 \
                  7.0-cudnn4

include ../../mk/cuda.mk
