# Copyright (c) 2016, NVIDIA CORPORATION. All rights reserved.

CUDA_SAMPLES := bandwidthTest \
                deviceQuery \
                matrixMulCUBLAS \
                vectorAdd \
                nvidia-smi

include ../../mk/samples.mk
